name: Docker-push
on:
  release:
    # Publish tagged image.
    types: [published]


jobs:
   # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_PATH: "cgerull/testserver"
      IMAGE_TAG: "null"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Print GitHub environment
        run: |
          echo $GITHUB_ENV
          cat $GITHUB_ENV
          echo "-------------------------"
          echo "IMAGE_PATH - ${{ env.IMAGE_PATH }}"
          echo "IMAGE_TAG - ${{ env.IMAGE_TAG }}"
          echo "IMAGE_NAME - ${{ env.IMAGE_NAME }}"
      - name: Set image name and version
        run: |
          # # Strip git ref prefix from version
          if [ $(echo "${{ github.ref }}" | grep tags) ]; then
            VER=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')
            echo "Found TAG"
          else
            VER=latest
            echo "No TAG found, Use latest"
          fi
          echo "Use TAG - $VER"
          echo "IMAGE_TAG=$VER" >> $GITHUB_ENV
      - name: Print GitHub environment
        run: |
          echo $GITHUB_ENV
          cat $GITHUB_ENV
          echo "-------------------------"
          echo "IMAGE_PATH - ${{ env.IMAGE_PATH }}"
          echo "IMAGE_TAG - ${{ env.IMAGE_TAG }}"
          echo "IMAGE_NAME - ${{ env.IMAGE_NAME }}"
      - name: Build new image name
        run: |
          IMAGE_NAME="${{ env.IMAGE_PATH }}:${{ env.IMAGE_TAG }}"
          echo "IMAGE_NAME - $IMAGE_NAME"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_NAME from env - ${{ env.IMAGE_NAME }}"
      - name: Print GitHub environment
        run: |
          echo $GITHUB_ENV
          cat $GITHUB_ENV
          echo "-------------------------"
          echo "IMAGE_PATH - ${{ env.IMAGE_PATH }}"
          echo "IMAGE_TAG - ${{ env.IMAGE_TAG }}"
          echo "IMAGE_NAME - ${{ env.IMAGE_NAME }}"

